// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8EQq0Le07oDggtfnBmX3AGa7gglKDFU4',
    appId: '1:981417554707:web:308afccdf716dca1bde0e6',
    messagingSenderId: '981417554707',
    projectId: 'trashtalk3003',
    authDomain: 'trashtalk3003.firebaseapp.com',
    storageBucket: 'trashtalk3003.firebasestorage.app',
    measurementId: 'G-41YWN6HKBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAcf2L7NJvrULrINDO2Tzm27N4FjkWszM',
    appId: '1:981417554707:android:e95b0adb4fe74864bde0e6',
    messagingSenderId: '981417554707',
    projectId: 'trashtalk3003',
    storageBucket: 'trashtalk3003.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg-9rrIollpvfHR5Q1ypgTEJnJOjEPXbg',
    appId: '1:981417554707:ios:2cab6b5270a82185bde0e6',
    messagingSenderId: '981417554707',
    projectId: 'trashtalk3003',
    storageBucket: 'trashtalk3003.firebasestorage.app',
    iosBundleId: 'com.example.binit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg-9rrIollpvfHR5Q1ypgTEJnJOjEPXbg',
    appId: '1:981417554707:ios:2cab6b5270a82185bde0e6',
    messagingSenderId: '981417554707',
    projectId: 'trashtalk3003',
    storageBucket: 'trashtalk3003.firebasestorage.app',
    iosBundleId: 'com.example.binit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8EQq0Le07oDggtfnBmX3AGa7gglKDFU4',
    appId: '1:981417554707:web:2f570b78ddd5eaefbde0e6',
    messagingSenderId: '981417554707',
    projectId: 'trashtalk3003',
    authDomain: 'trashtalk3003.firebaseapp.com',
    storageBucket: 'trashtalk3003.firebasestorage.app',
    measurementId: 'G-V73WBQZW4V',
  );
}
